### ISSUE TITLE
请教下大神， Outliner 部分用的是什么技术栈呀？自己开发的吗？

### ISSUE THREAD

**Issue by liangxieq** [awehook/blink-mind-package#2]
请教下大神， Outliner 部分用的是什么技术栈呀？自己开发的吗？

现在想给自己的网站集成类似 workflowy 那种的大纲编辑功能，找不到比较好的开源实现。

下载了 awesome-outliner，awesome-outliner 的实现比较完善。

**Comment by awehook** [comment]
技术栈是React + immutable.js, 核心部分的代码已经在https://github.com/awehook/blink-mind 这个仓库里面开源了

**Comment by liangxieq** [comment]
谢谢
